#include <boost/preprocessor.hpp>


#define DECLARE_DATA_MEMBER(R,TYPES,INDEX,NAME) BOOST_PP_SEQ_ELEM(INDEX,TYPES) BOOST_PP_CAT(NAME,_);

#define DEFINE_GET_ACCESSOR(R,TYPES,INDEX,NAME) BOOST_PP_SEQ_ELEM(INDEX,TYPES) BOOST_PP_CAT(get_,NAME)(){ return BOOST_PP_CAT(NAME,_); }

#define DEFINE_SET_ACCESSOR(R,TYPES,INDEX,NAME) void BOOST_PP_CAT(set_,NAME)(BOOST_PP_SEQ_ELEM(INDEX,TYPES) value) { BOOST_PP_CAT(NAME,_)=value; }

#define MY_MACRO(TYPES,NAMES) \
BOOST_PP_SEQ_FOR_EACH_I(DECLARE_DATA_MEMBER,TYPES,NAMES) \
public: \
BOOST_PP_SEQ_FOR_EACH_I(DEFINE_GET_ACCESSOR,TYPES,NAMES) \
BOOST_PP_SEQ_FOR_EACH_I(DEFINE_SET_ACCESSOR,TYPES,NAMES)
struct A
{
    MY_MACRO((int)(float)(double),(x)(y)(z))
};
